#!/bin/bash
PID=$(ps -ef | grep demo-0.0.1-SNAPSHOT | grep -v grep | awk '{ print $2 }')
if [ -z "$PID" ]
then
  echo demo-0.0.1-SNAPSHOT is already stopped
else
  echo kill $PID
  kill $PID
fi

rm -rf /usr/local/test/spring.log

nohup java -jar /usr/local/test/demo-0.0.1-SNAPSHOT.jar >> /usr/local/test/spring.log --server.port=9999 &

#sleep 10
#cat /usr/local/test/spring.log
tail -1f /usr/local/test/spring.log|sed '/Started DemoApplication in/Q'
