#!/bin/bash
echo "启动开始"
PID=$(ps -ef | grep demo-0.0.1-SNAPSHOT | grep -v grep | awk '{ print $2 }')
if [ -z "$PID" ]
then
  echo demo-0.0.1-SNAPSHOT is already stopped
else
  echo kill $PID
  kill $PID
fi


nohup java -jar /usr/local/test/demo-0.0.1-SNAPSHOT.jar --server.port=9999 &

sleep 1

tail -n 800 /usr/local/test/spring.log